### PR TITLE
add default params for raw_value messages and values 

### PR DESCRIPTION
**Pull request by vordimous**

### CODE REVIEW

**Comment by vordimous** [comment]
@DamascenoRafael do you have a chance to review this proposed change?

**Comment by DamascenoRafael** [comment]
Hey @vordimous, sorry for taking so long, I took some time off.

I ran the examples here to understand the behavior of the new parameters and I understood. But would you mind explaining the use case for them (or the scenarios in which these parameters would be useful)?

**Comment by vordimous** [comment]
Sure thing @DamascenoRafael, I hope you had a great time off! 

You probably noticed it just gives some more flexibility around adding static and default parameters for each value. These changes came from the [demo](https://github.com/aklivity/zilla-demos/tree/main/taxi) I made.

For the `VALUE_DEFAULT` option, the quantitative benefit here is to reduce the overall size of the config when all of the message payloads have the same value with a few variations. A practical benefit comes when actively developing logic on the consumer side. Testing and updating 100+ prebuilt messages with different values is cumbersome. I am not using this feature currently but can see how it would be useful while I was working with some [load testing configs](https://github.com/aklivity/zilla-demos/blob/main/taxi/grpc/service/default_routes_load_test.json).

For the `PAYLOAD_ROOT` option, is more of a workaround given the json payload has the `DATA.NAME` attribute as the parameter key on every message. I can see where this could be solved with a larger change but didn't want to go down that rabbit hole. I am using this code already here: https://github.com/aklivity/zilla-demos/tree/main/taxi/grpc/service

**Comment by vordimous** [comment]
@DamascenoRafael, just wanted to bring you attention back to this if you have the capacity to review it.

**Comment by DamascenoRafael** [comment]
Merging, but I'm planning some changes to simplify the code.

**Comment by vordimous** [comment]
> Merging, but I'm planning some changes to simplify the code.

Looking forward to them!

**Pull request merged**
